#ifndef NOT_LU_INFO_DSC_h
#define NOT_LU_INFO_DSC_h
const LUInInfoDsc ar_n_Not_Dsc[MAX_AMOUNT_LU_NOT] = {
//Param for 
{1,ORD_INPUT_01,STNG_LU_INPUT}//,{STNG_LU_INPUT,ORD_INPUT_02,1}
//{STNG_LU_INPUT,ORD_INPUT_07,1},{STNG_LU_INPUT,ORD_INPUT_08,1}




};

#endif 
