#ifndef OR_LU_INFO_DSC_h
#define OR_LU_INFO_DSC_h

const LUInInfoDsc ar_n_Or_Dsc[MAX_AMOUNT_LU_OR*8] = {
//Param for 
{1,ORD_INPUT_01,STNG_LU_INPUT},{1,ORD_INPUT_02,STNG_LU_INPUT},
{1,ORD_INPUT_03,STNG_LU_INPUT},{1,ORD_INPUT_04,STNG_LU_INPUT},
{1,ORD_INPUT_05,STNG_LU_INPUT},{1,ORD_INPUT_06,STNG_LU_INPUT},
{1,ORD_INPUT_07,STNG_LU_INPUT},{1,ORD_INPUT_08,STNG_LU_INPUT}




};

#endif 
