#ifndef __CONST_REGISTRATORS_MENU2__
#define __CONST_REGISTRATORS_MENU2__

enum __index_list_registrators_m2
{
  INDEX_LIST_REGISTRATORS_M2_ACTIONS = 0,
  INDEX_LIST_REGISTRATORS_M2_ERRORS,

  MAX_ROW_LIST_REGISTRATORS_M2
};

#endif
