#ifndef __CONST_LIST_SETTINGS_BIOS_MENU2__
#define __CONST_LIST_SETTINGS_BIOS_MENU2__

enum __index_list_settings_bios_m2
{
  INDEX_LIST_SETTINGS_BIOS_M2_INPUT = 0,
  INDEX_LIST_SETTINGS_BIOS_M2_OUTPUT,
  INDEX_LIST_SETTINGS_BIOS_M2_LED,
  
  MAX_ROW_LIST_SETTINGS_BIOS_M2
};


#endif
