#ifndef __CONST_STATE_INPUTS_OUTPUTS_MENU2__
#define __CONST_STATE_INPUTS_OUTPUTS_MENU2__

enum __index_input_output_m2
{
INDEX_INOUT_OUTPUT_M2_INPUT = 0,
INDEX_INOUT_OUTPUT_M2_OUTPUT,

MAX_ROW_INPUT_OUTPUT_M2
};

#endif
