#ifndef __CONST_MAIN_MENU2__
#define __CONST_MAIN_MENU2__

enum __index_main_m2
{
INDEX_MAIN_M2_TIME = 0,
INDEX_MAIN_M2_MEASURMENTS,
INDEX_MAIN_M2_INPUTS_OUTPUTS,
INDEX_MAIN_M2_REGISTRATORS,
INDEX_MAIN_M2_SETTINGS,
INDEX_MAIN_M2_DIAGNOSTYKA,
INDEX_MAIN_M2_SETTINGS_POINT,
INDEX_MAIN_M2_INFO,

MAX_ROW_MAIN_M2
};

#endif
