#ifndef __CONST_GLOBAL_TIMERS__
#define __CONST_GLOBAL_TIMERS__

enum _timers
{
  INDEX_TIMER_INPUT_START = 0,
  INDEX_TIMER_TEMP = (INDEX_TIMER_INPUT_START + NUMBER_INPUTS),

  MAX_NUMBER_GLOBAL_TIMERS
};

#endif
