#ifndef __CONST_GROUP_ALARMS_MENU2__
#define __CONST_GROUP_ALARMS_MENU2__

#define COL_PICKUP_GROUP_ALARM_DELTA_I_BEGIN             4
#define COL_PICKUP_GROUP_ALARM_DELTA_I_COMMA             5
#define COL_PICKUP_GROUP_ALARM_DELTA_I_END               8

#define COL_DELAY_GROUP_ALARM_DELAY_BEGIN                6
#define COL_DELAY_GROUP_ALARM_DELAY_COMMA                8
#define COL_DELAY_GROUP_ALARM_DELAY_END                  9

#define MASKA_CTRL_GROUP_ALARM_M2 ((1 << _MAX_INDEX_CTRL_GROUP_ALARM_BITS_SETTINGS) - 1)

#endif 
