#ifndef __CONST_LABELS_MENU2__
#define __CONST_LABELS_MENU2__

enum __index_labels_m2
{
  INDEX_LABELS_M2_CONFIGURATION = 0,
  INDEX_LABELS_M2_SETTINGS,
  
  MAX_ROW_LABELS_M2
};

#define MAX_ROW_TIME_CONFIG_OR_SETTINGS      1 

#endif
