#ifndef __CONST_LIST_SETTINGS_MENU__
#define __CONST_LIST_SETTINGS_MENU__

enum __index_list_settings_m2
{
  INDEX_LIST_SETTINGS_M2_CONFIGURATION = 0,
  INDEX_LIST_SETTINGS_M2_BIOS,
  INDEX_LIST_SETTINGS_M2_ALARMS,
  INDEX_LIST_SETTINGS_M2_GROUP_ALARMS,
  INDEX_LIST_SETTINGS_M2_TIMERS,
  INDEX_LIST_SETTINGS_M2_MEANDER,
  INDEX_LIST_SETTINGS_M2_PARAMETRIZATION,
  INDEX_LIST_SETTINGS_M2_LANGUAGE,
  INDEX_LIST_SETTINGS_M2_COMMUNICATION,
  INDEX_LIST_SETTINGS_M2_PASSWORDS,
  
  MAX_ROW_LIST_SETTINGS_M2
};

#endif
