#ifndef __CONST_PARAM_LIST_LOGICAL_NODES_MENU2__
#define __CONST_PARAM_LIST_LOGICAL_NODES_MENU2__

#define MAX_ROW_FOR_PARAM_LIST_LOGICAL_NODES  NUMBER_ALL_BLOCKS

enum _index_param_list_logical_nodes_m2
{
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_GENERAL_BLOCK = 0,
  INDEX_PARAM_LIST_LOGICAL_NODES_M2_OTHERS,
  
  MAX_ROW_PARAM_LIST_LOGICAL_NODES_M2
};



#endif
